### ISSUE TITLE
error in spatial normalization

### ISSUE THREAD

**Issue by macshine** [poldrack/fmri-analysis-vm#14]
Hey guys

While running through the 'spatial normalization' ipython notebook, I got an error during the 'ANTS' section. Here's the error message:

NameError
<ipython-input=1-1c0b2cf8cd10> in <module>()
----> 1 ants_reg = mem.cache(ants.Registration)
        2 ants_results = ants_reg(fixed_image = os.path.join(os.getenv('FSLDIR'),'data/standard/MNI152_T1_2mm_brain.nii.gz'),
        3                                 moving_image = bet_results.output.out_file,

**Comment by macshine** [comment]
... (sorry, I pushed 'enter' before I was ready...)

NameError: name 'mem' is not defined

**Comment by vsoch** [comment]
I think you need something like:

```
  mem = Memory(cachedir='/tmp/analyses/cache')
```

**Comment by poldrack** [comment]
See the preprocessing code to get the right temp directory

**Comment by vsoch** [comment]
This guy!

```
  mem = Memory(base_dir='.')
```

**Comment by poldrack** [comment]
no  - we use a specific directory for caching

> On Aug 24, 2015, at 4:11 PM, vsoch notifications@github.com wrote:
> 
> This guy!
> 
>   mem = Memory(base_dir='.')
> —
> Reply to this email directly or view it on GitHub https://github.com/poldrack/fmri-analysis-vm/issues/14#issuecomment-134407994.

—
Russell A. Poldrack
Professor of Psychology
Bldg. 420, Jordan Hall
Stanford University
Stanford, CA 94305

poldrack@stanford.edu
http://www.poldracklab.org/

**Comment by poldrack** [comment]
sorry, I guess you were right!

> On Aug 24, 2015, at 4:11 PM, vsoch notifications@github.com wrote:
> 
> This guy!
> 
>   mem = Memory(base_dir='.')
> —
> Reply to this email directly or view it on GitHub https://github.com/poldrack/fmri-analysis-vm/issues/14#issuecomment-134407994.

—
Russell A. Poldrack
Professor of Psychology
Bldg. 420, Jordan Hall
Stanford University
Stanford, CA 94305

poldrack@stanford.edu
http://www.poldracklab.org/

**Comment by poldrack** [comment]
fixed in latest push
