### ISSUE TITLE
error importing 'seaborn' in 'statistics' notebook

### ISSUE THREAD

**Issue by macshine** [poldrack/fmri-analysis-vm#15]
ImportError: No module named seaborn

**Comment by poldrack** [comment]
import seaborne should do it

> On Aug 24, 2015, at 4:17 PM, Mac Shine notifications@github.com wrote:
> 
> ImportError: No module named seaborn
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/poldrack/fmri-analysis-vm/issues/15.

—
Russell A. Poldrack
Professor of Psychology
Bldg. 420, Jordan Hall
Stanford University
Stanford, CA 94305

poldrack@stanford.edu
http://www.poldracklab.org/

**Comment by macshine** [comment]
It didn't like that either:

"ImportErorr: No module named seaborn"

**Comment by macshine** [comment]
To clarify, I tried to run the first step of the notebook, which includes the line:

'import seaborn as sn'

but it can't find it...

**Comment by poldrack** [comment]
hmm, I guess we forgot to install seaborn!  will have to add it in manually (which you can do using “pip install seaborn”)

cheers
rp

> On Aug 24, 2015, at 4:18 PM, Mac Shine notifications@github.com wrote:
> 
> It didn't like that either:
> 
> "ImportErorr: No module named seaborn"
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/poldrack/fmri-analysis-vm/issues/15#issuecomment-134409912.

—
Russell A. Poldrack
Professor of Psychology
Bldg. 420, Jordan Hall
Stanford University
Stanford, CA 94305

poldrack@stanford.edu
http://www.poldracklab.org/

**Comment by poldrack** [comment]
added instruction on installing seaborn to README
