### ISSUE TITLE
NameError in BayesianGLM

### ISSUE THREAD

**Issue by macshine** [poldrack/fmri-analysis-vm#16]
NameError: name 'pym3' is not defined.

**Comment by poldrack** [comment]
you sure it wasn’t “pymc3”?

> On Aug 24, 2015, at 4:30 PM, Mac Shine notifications@github.com wrote:
> 
> NameError: name 'pym3' is not defined.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/poldrack/fmri-analysis-vm/issues/16.

—
Russell A. Poldrack
Professor of Psychology
Bldg. 420, Jordan Hall
Stanford University
Stanford, CA 94305

poldrack@stanford.edu
http://www.poldracklab.org/

**Comment by poldrack** [comment]
added pymc3 import in latest push - do "git pull origin master" to grab the fix

**Comment by macshine** [comment]
Yep, that was it. Sorry for the typo.
